### PR TITLE
rename katello_publish

### PR DESCRIPTION
**Pull request by sean797**
Obviously a breaking change but the sooner the better

### CODE REVIEW

**Comment by akofink** [comment]
Before we merge, are there any other projects that we should submit PRs to to update the name of this module? (see robotello-ci PR above).

**Comment by mdellweg** [comment]
Is there a way to add an alias with the old name?

**Comment by akofink** [comment]
I can't see it in the docs/using Google. I'm asking in IRC (#ansible on freenode).

**Comment by sean797** [comment]
There is https://github.com/sean797/ansible-role-configure-katello/blob/master/handlers/main.yml#L14 but I'll commit that when this is merged.

Are we okay with this without a deprecation? I guess I could leave the old module and make it print a failed message saying to use the new name.

**Comment by akofink** [comment]
I'm fine with the name change and no deprecation. I don't think we have that many people using this repo in production yet. @ehelms Good with that?

**Comment by mdellweg** [comment]
Maybe we trigger an unintended user survey. ;) I'm good.

**Pull request merged**
