### PR TITLE
Fix repository to update URL if it changes

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by ehelms** [comment]
@akofink care to review?

**Comment by ohadlevy** [comment]
trigging pr status to test travis.

**Comment by akofink** [comment]
`type` isn't supported, even though it's used in the example. That kind of limits further testing. Mind fixing it while you're in here?

**Comment by akofink** [comment]
I see now that `content_type` *does* work. Still, the example needs to be updated. Indeed, the URL change works now.

**Pull request merged**
