### PR TITLE
add changelog for issue #927

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Comment by evgeni** [comment]
@hlawatschek :see_no_evil: we forgot to add a changelog entry :D

**Comment by hlawatschek** [comment]
Oh... thanks for fixing this :-)

**Comment by evgeni** [comment]
@hlawatschek no worries, the new changelog process is still a bit muddy.

would you mind acking this PR? :)

**Review by hlawatschek — APPROVED** [review]
ACK

**Pull request merged**
