### PR TITLE
Add a filter to produce candle_pin labels

### PR DESCRIPTION
**Pull request by mdellweg**

### CODE REVIEW

**Comment by sean797** [comment]
Whats the use case for this?

**Comment by mdellweg** [comment]
When you create products and repositories with certain names, you can use this to construct the corresponding urls.

**Comment by sean797** [comment]
Are we better getting it from the API since the user can customise it? 

Screenshot from 2019-08-29 11-09-22

**Comment by mdellweg** [comment]
I think both ways are valid.

**Comment by mdellweg** [comment]
I must admit, at least partially i wanted to write _a_ filter. But also, we use this one.

**Pull request merged**
