### PR TITLE
fix notes rendering in templates_import module

### PR DESCRIPTION
**Pull request by evgeni**
with the | it just renders the first line as a note

### CODE REVIEW

**Comment by evgeni** [comment]
@nesanton did I mention I hate YAML? :)

**Comment by evgeni** [comment]
before:
Screenshot from 2020-04-20 14-32-02

after:
Screenshot from 2020-04-20 14-31-53

**Comment by nesanton** [comment]
oh I'm sorry. I felt like making it one line (per your initial suggestion) then found that it hurts my eyes, then grep -r 'notes:'  to see if any other module has such issues, and after finding out that I'm alone landed with the |.

TIL, LGTM

**Comment by evgeni** [comment]
no worries, YAML is just that horrible :)

**Pull request merged**
