### PR TITLE
release 2.2.0

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Comment by Fodoj** [comment]
image

**Review by mdellweg — APPROVED** [review]

**Comment by mdellweg** [comment]
That's a hell of an error message: `ERROR! Unexpected Exception, this is probably a bug: 'results'`
Can we call it a misfire and just move on?

**Comment by evgeni** [comment]
>  Can we call it a misfire and just move on?

that's exactly what I was about to do!

**Comment by evgeni** [comment]
released @ https://galaxy.ansible.com/theforeman/foreman

FTR, there will be galaxy maintenance in like 5 minutes, for up to 3 hours, so things might not work :)

**Pull request merged**
