### PR TITLE
patch apidoc to include rex proxy ids for subnets

### PR DESCRIPTION
**Pull request by evgeni**
Fixes: #428

### CODE REVIEW

**Comment by m-czernek** [comment]
I applied the patch and tested in my environment. It fixes the fact that:

- update calls are not idempotent
- remote execution proxy settings is ignored in the create calls

**Comment by evgeni** [comment]
@bagasse @mdellweg thoughts? What I don't like is that this is applied *always*, not only to setups that actually have REX enabled. But this shouldn't be a problem?

**Comment by evgeni** [comment]
@m-czernek can you try the latest version of this? should work just fine on your setup, but avoid patching when REX is not installed.

**Comment by m-czernek** [comment]
I have this in my mind. I'm now working on something different, but will definitely test this within the next week.

**Comment by mdellweg** [comment]
Is this part of api only missing in the saved apidoc from a plain foreman without rex?

**Comment by evgeni** [comment]
No, this is missing from instances with REX installed too, see https://projects.theforeman.org/issues/19086

**Comment by evgeni** [comment]
@m-czernek I'll merge this now. Feel free to yell at me if it turns out it doesn't work for you.

**Comment by m-czernek** [comment]
@evgeni Just wanted to get back to you, this still works (tested it today against master).

It's slightly unfortunate that the exit value is always `changed`, but that's a very minor thing.

Thank you once again!

**Comment by evgeni** [comment]
The exit is always changed? Mhh. I'll have to look at that. But later ;)

**Comment by evgeni** [comment]
Oh right, of course it is, the api doesn't answer with the id eitjer

**Pull request merged**
