### PR TITLE
Use consistent parameters in subnet module documentation

### PR DESCRIPTION
**Pull request by quba42**
This fixes what appears to be a incompletely amended copy and paste error in the `foreman_subnet` module.

I also changed the parameter names in the example to be in line with the parameters from the documentation.

### CODE REVIEW

**Comment by quba42** [comment]
I see I will have to fix some tests...

**Comment by mdellweg** [comment]
The corresponding Nailgun part changed a month ago:
https://github.com/SatelliteQE/nailgun/commit/03e604149c774a163dba66efd2f9b0ce471ed405

**Comment by mdellweg** [comment]
Try just rerecording.

**Comment by quba42** [comment]
Turns out I had this backwards. The underscore is needed for current nailgun (I was accidentally not using newest nailgun, ups).

I have undone the change, but this PR can still stand for the config file change.

**Comment by quba42** [comment]
Let me still change the commit message.

**Comment by quba42** [comment]
The commit message now reflects the changed nature of the PR.

**Pull request merged**
