### PR TITLE
Rename cement states

### PR DESCRIPTION
**Pull request by mdellweg**
fixes: https://github.com/theforeman/foreman-ansible-modules/issues/30

### CODE REVIEW

**Comment by mdellweg** [comment]
@evgeni @akofink @ehelms : is there any consensus whether this is a viable option. I could do the rebasing and updating for even more modules, if it were worth the time.

**Comment by akofink** [comment]
Yeah, I'm not crazy about the `present_with_defaults` name, but I can live with it (I don't have a better idea).

**Comment by mdellweg** [comment]
@akofink rebased

**Comment by akofink** [comment]
Not sure why we let this sit for so long.

**Pull request merged**
