### PR TITLE
don't scope create/update requests by Organization/Location

### PR DESCRIPTION
**Pull request by evgeni**
Foreman/Apipie allows the same short parameter name to be used multiple
times in an API definition and we fill them identically, assuming they
mean the same.
However, this is not true. For example, when creating a Host, the "outer"
organization_id means to "scope" the request by that ID, while the
"inner" says that the Host is to be created in said Organization.
While this does not negatively affect Host *creation*, you cannot
*update* a Host to be moved into a different Organization.

### CODE REVIEW

**Comment by evgeni** [comment]
Draft because I didn't update the tests and would like some feedback on the (rather hacky) approach before continuing.

There is sadly no information in the APIdoc what the *use* of a specific param is, so I refrained from putting this into `apypie`.

**Comment by mdellweg** [comment]
Is the main diffference here, that one is a url parameter and the other is supposed to go into the body payload?
Do we even need to care for the scoping of queries here?

**Comment by evgeni** [comment]
```
FAILED tests/test_crud.py::test_crud[host_interface_attributes]
FAILED tests/test_crud.py::test_crud[host]
FAILED tests/test_crud.py::test_crud[scc_account]
```

I have expected to break more tests with this change :rofl:

**Comment by evgeni** [comment]
> Is the main diffference here, that one is a url parameter and the other is supposed to go into the body payload?
> Do we even need to care for the scoping of queries here?

No, both go into the JSON body:

bad (old):
```json
{"location_id": 16, "organization_id": 15, "host": {"name": "test-host.example.net", "location_id": 16, "organization_id": 15, "build": false, "managed": false}}
```

good (new):
```json
{"host": {"name": "test-host.example.net", "location_id": 16, "organization_id": 15, "build": false, "managed": false}}
```

**Comment by mdellweg** [comment]
So we could "hot patch" the docs "fam style" to never use the outer appearance?

**Comment by evgeni** [comment]
We probably could, both sounds like a hack :(

**Comment by ehelms** [comment]
Conceptually this makes sense to me to do.

**Comment by evgeni** [comment]
Updated to use doc patching, seems more straight forward and scoped.

**Review by ehelms — APPROVED** [review]

**Review by mdellweg — APPROVED** [review]

**Pull request merged**
