### PR TITLE
simplify report config

### LINKED ISSUE #1072: simplify inventory configuration
I still dislike the `dict` based config, so I thought we could move it (all the params we have in `reporting` and `foreman`) to the "main" level and then provide some code that will look into the `reporting` and `foreman` dicts to remain compatible with the old style.

_Originally posted by @evgeni in https://github.com/theforeman/foreman-ansible-modules/issues/986#issuecomment-731112931_

### LINKED ISSUE #1076: inventory documentation broken
##### SUMMARY
https://theforeman.github.io/foreman-ansible-modules/develop/plugins/foreman_inventory.html#ansible-collections-theforeman-foreman-foreman-inventory

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```

```

##### COLLECTION VERSION

```

```

##### KATELLO/FOREMAN VERSION

```

```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

### PR DESCRIPTION
**Pull request by evgeni**
this is so far untested by me

### CODE REVIEW

**Comment by evgeni** [comment]
@sjha4 can you please have a look?

**Comment by sjha4** [comment]
So the intent is to allow having these configs outside the foreman and report nesting while maintaining backward compatibility right? I tested that part and it works the old and new way.. :smile:

**Comment by evgeni** [comment]
Correct, yeah! It also (accidentally) fixes the bad doc rendering (see #1076).

**Review by sjha4 — APPROVED** [review]
Works as advertised. Able to handle dict and non-dict options. :+1:

**Pull request merged**
