### PR TITLE
Release 3.4.0

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Review by mdellweg — APPROVED** [review]

**Comment by gardar** [comment]
Seems like this release hasn't made it in the [yum repo](http://yum.theforeman.org/plugins/latest/) yet, any chance that could be fixed?

**Comment by evgeni** [comment]
> Seems like this release hasn't made it in the [yum repo](http://yum.theforeman.org/plugins/latest/) yet, any chance that could be fixed?

That's not *entirely* correct, it *is* available in the `nightly` repo, but I see your point. I'll do the backports :)

**Comment by gardar** [comment]
Ah, well one would expect the `nightly` repo to be the latest `development` version, and the `latest` repo to contain the latest stable version.
Also the `nightly` repo isn't available on el7, so it's unavailable for those of us that are stuck with redhat satellite on el7.

**Comment by evgeni** [comment]
Packages were built for 3.3 (which is what latest currently points at) and should be available in the repos in the next few hours!

**Pull request merged**
