### PR TITLE
lint everything, not just roles

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Review by ekohl — COMMENTED** [review]
:+1: to this, but looks like you made it unhappy.

**Comment by evgeni** [comment]
My name is Evgeni and I make linters unhappy.

**Comment by evgeni** [comment]
:tada:

**Comment by evgeni** [comment]
```
ERROR: plugins/inventory/foreman.py:186:1: unparsable-with-libyaml: expected a single document in the stream - but found another document
```

GO FUCK YOURSELF

**Review by ekohl — APPROVED** [review]

**Pull request merged**
