### PR TITLE
don't set entity_name in product module

### PR DESCRIPTION
**Pull request by evgeni**
it can be derived from the class name just fine

### CODE REVIEW

**Comment by evgeni** [comment]
things you find while looking for examples for a demo :)

**Review by Griffin-Sullivan — APPROVED** [review]

**Comment by Griffin-Sullivan** [comment]
does it use the class name or the name of the file?

**Comment by evgeni** [comment]
Class name

**Comment by Griffin-Sullivan** [comment]
is the class name not KatelloProductModule?

**Comment by evgeni** [comment]
It is. And the code strips `Katello` and `Module` and then transforms the rest:

https://github.com/theforeman/foreman-ansible-modules/blob/b526b1ac7a68bd763a7fad481c8e1aadc25c27d5/plugins/module_utils/foreman_helper.py#L1336-L1356

**Pull request merged**
