### PR TITLE
cache python dependencies for quicker setup

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Comment by evgeni** [comment]
mhh, no, this can be simplified to use less caches
- the ansible version is irrelevant (we won't cache that anyways)
- the checkmode vs build jobname is irrelevant

**Comment by mdellweg** [comment]
What is being cached here? The package list of pip and the downloaded packages? Can't we just reuse the same cache for all jobs?

**Comment by evgeni** [comment]
This caches `~/.cache/pip` which contains whatever `pip` downloaded from pypi.org (so wheels and stuff). But really just the downloads, the dependency resolution and installation still happens "live".

My reasoning behind using different caches was that different steps use a different set of packages, and thus re-using a cache from the docs step is "bad" in the normal test step, as that would mean to re-download all the non-docs deps (as the docs step didn't cache them).

**Comment by evgeni** [comment]
but at least the python version should be irrelevant, we have few deps that *differ* based on python version.

**Comment by mdellweg** [comment]
Wouldn't that just give a cache containing all the wheels for tests and docs? And therefore be good for everyone?

I still don't see, who saves the cache, and whether it's augmented by each job. Is it cached across runs?

**Comment by evgeni** [comment]
`actions/cache` has a "post" step (so you don't see it in the workflow definition) that collects the cache

and yeah, you're right, the "worst" that'd happen is we seed the cache too much and then only partially update it.

**Review by mdellweg — APPROVED** [review]
Not that i fully understand the mechanics, but this looks reasonable.

**Pull request merged**
