### PR TITLE
possibility to pass flags to test_ and record_ makefile entries

### PR DESCRIPTION
**Pull request by pondrejk**
needed for harvesting junit.xml files from pytest

### CODE REVIEW

**Review by mdellweg — COMMENTED** [review]
I would have expected to see this a the "test" target. Not so much at the "record_%".
Can you set the variable to empty? I think there is a strict mode where Make fails on undefined references.

**Comment by pondrejk** [comment]
> I would have expected to see this a the "test" target. Not so much at the "record_%".
> Can you set the variable to empty? I think there is a strict mode where Make fails on undefined references.

Empty declaration added. I need this on the record for live mode

**Comment by evgeni** [comment]
3.5 failure should be "fixed" by https://github.com/theforeman/foreman-ansible-modules/pull/937

**Comment by evgeni** [comment]
"it's fine"

**Review by evgeni — APPROVED** [review]

**Pull request merged**
