### PR TITLE
add make record-crud

### PR DESCRIPTION
**Pull request by pondrejk**
makefile option to re-record responses for all crud tests

### CODE REVIEW

**Comment by evgeni** [comment]
Hey,

what's the use case here? Do far I never had to re-record all in one go.

Do you rather want to run the tests against a live instance, ignoring the records?

**Comment by pondrejk** [comment]
> 
> Do you rather want to run the tests against a live instance, ignoring the records?

Yes, basically I want that, though I thought having the records from the run might come handy in the future, for example if the upstream/downstream test sets start to diverge.

**Comment by evgeni** [comment]
So I think I would prefer a `live` fixture that works similarly as our current `record` one instead. But:
- I'm not opposed to having both in (as I see a certain use of having the newly recorded results if one is analysing some issue)
- I'm not going to implement `live` just now.

cc @mdellweg who wrote a big chunk of the whole VCR test setup and might have opinions.

**Comment by mdellweg** [comment]
I am not against it per se, but i fear people will open pr's with _all_ fixtures regenerated without the need for it.
With a small bash loop, you can automatically regenerate all tests that fail.
The `test_live` sounds like a valueable addition regardless.

**Comment by pondrejk** [comment]
Closing as this approach causes clashes between tests in setup and teardown phases, using loop with record_[item] instead

**Pull request closed without merging**
