### PR TITLE
Repository test fixes

### PR DESCRIPTION
**Pull request by Griffin-Sullivan**
Made some fixes to repository related testing. I also added some small changes to other test files like commenting the test requirements. 

repositories_role.yml: Needed a manifest to sync RH products

(NEW) repositories_role_deb.yml: Deb is not a repo type in Satellite, so I made a new file for it

repository.yml: There's a lot of checks for expected_change that fail, because Ansible is reporting changes no matter what. I decided to just remove these checks, but we could also look deeper into other ways to check that the test objects aren't changing when they aren't supposed to.

repository_sync.yml: Needed a repo_url to sync from.

### CODE REVIEW

**Comment by evgeni** [comment]
No, nothing of the removed should have produced wrong expected changes.

Do you happen to have the output *what* changed?

**Comment by Griffin-Sullivan** [comment]
```yaml
- include_tasks: tasks/repository.yml
          vars:
            repository_state: present
            repository_mirror_on_sync: false
            expected_change: false
```
```
changed: [tests] => {
    "changed": true,
    "diff": {
        "after": {
            "repositories": [
                {
                    "arch": "noarch",
                    "content_type": "yum",
                    "download_policy": "immediate",
                    "http_proxy_policy": "global_default_http_proxy",
                    "id": 32,
                    "label": "just_a_test_repo",
                    "mirroring_policy": "additive",
                    "name": "Test Repository",
                    "organization_id": 7,
                    "os_versions": [],
                    "product_id": 58,
                    "unprotected": true,
                    "url": "https://repos.fedorapeople.org/pulp/pulp/demo_repos/zoo/",
                    "verify_ssl_on_sync": true
                }
            ]
        },
        "before": {
            "repositories": [
                {
                    "arch": "noarch",
                    "content_type": "yum",
                    "download_policy": "immediate",
                    "http_proxy_policy": "global_default_http_proxy",
                    "id": 32,
                    "label": "just_a_test_repo",
                    "mirroring_policy": "additive",
                    "name": "Test Repository",
                    "organization_id": 7,
                    "os_versions": [],
                    "product_id": 58,
                    "unprotected": true,
                    "url": "https://repos.fedorapeople.org/pulp/pulp/demo_repos/zoo/",
                    "verify_ssl_on_sync": true
                }
            ]
        }
    },
}
Read vars_file 'vars/server.yml'

TASK [assert] ******************************************************************
task path: /foreman-ansible-modules/tests/test_playbooks/tasks/repository.yml:36
fatal: [tests]: FAILED! => {
    "assertion": "result.changed == expected_change",
    "changed": false,
    "evaluated_to": false,
    "msg": "Ensuring repository is present failed! (expected_change: False)"
}
```

**Comment by evgeni** [comment]
What system are you running this against? A Satellite 6.11?

**Comment by Griffin-Sullivan** [comment]
6.12

**Comment by Griffin-Sullivan** [comment]
I see the same error on 6.11 as well.

**Comment by evgeni** [comment]
Okay, I know where the expected_chage failures come from, fixing them now instead of deleting ;)

**Comment by evgeni** [comment]
The idempotency failures should be fixed by https://github.com/theforeman/foreman-ansible-modules/pull/1487
And then there are additional fixes needed to run the tests against Katello 4.5: https://github.com/theforeman/foreman-ansible-modules/pull/1488

**Comment by Griffin-Sullivan** [comment]
Ok I took out the repository test changes.

**Comment by evgeni** [comment]
Thanks @Griffin-Sullivan! And sorry I forgot to look at this PR again.

What was missing is to re-record the tests, as you did change them (see https://github.com/theforeman/foreman-ansible-modules/blob/develop/docs/testing.md), I did that now, and will merge the PR once CI is green.

**Review by evgeni — APPROVED** [review]

**Pull request merged**
