### PR TITLE
drop metadata, it's not needed inside a collection

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Comment by mdellweg** [comment]
I think you forgot the filter plugin here.

**Comment by evgeni** [comment]
> I think you forgot the filter plugin here.

ofcourse I did

**Comment by evgeni** [comment]
For @gundalow: https://github.com/ansible-collections/overview/issues/45#issuecomment-627922948

**Comment by gundalow** [comment]
Thank you :)

**Pull request merged**
