### PR TITLE
Remove shadow entities

### PR DESCRIPTION
**Pull request by mdellweg**
* Remove the shadowing entity for global parameter, as the functionality has been added to nailgun.
* Import entities directly from nailgun if they are not modified in cement.

### CODE REVIEW

**Comment by mdellweg** [comment]
Maybe, i can draw you attention to another PR ;) @akofink

**Comment by akofink** [comment]
Could you please add a description to this PR?

**Comment by mdellweg** [comment]
Something like this?

**Comment by mdellweg** [comment]
Honestly i have never heard of shadowing classes before. It was a dirty hack for us to not needing to wait for the inclusion in nailgun. So this is really only cleanup.
There is more to come around the Compute* classes, but i'd like to do this refactoring, once the corresponding unittests are in place.

**Pull request merged**
