### PR TITLE
add affects_multiple option to installation medium

### PR DESCRIPTION
**Pull request by manuelbonk**

### CODE REVIEW

**Comment by sean797** [comment]
For clarification, this allows us to set the name to `*` and then it will update every entity?

**Comment by manuelbonk** [comment]
Correct, a feature thats also present in the ptable, provisioning template and job template module.

**Comment by mdellweg** [comment]
From the top of my head:
* Delete all entities
* assign all entities to a taxonomy

**Comment by sean797** [comment]
I would prefer if this was DRY'd, moving the logic to `ansible_nailgun_cement`, it seems like a large change to make to each module and a lot of code to maintain

**Comment by mdellweg** [comment]
I'd be fine with merging this as is. Then we had three instances with test coverage (together with #242 ). That should allow for a stable refactoring.

**Comment by manuelbonk** [comment]
> Can you add something to the module documentation?

:white_check_mark:

**Comment by mdellweg** [comment]
:+1: for the test.

**Comment by manuelbonk** [comment]
added some tests @sean797 requested.

**Comment by mdellweg** [comment]
Tests look perfect. Given three ACKs, i am goining to merge this now.

**Pull request merged**
