### PR TITLE
Fail old test playbooks using localhost

### PR DESCRIPTION
**Pull request by mdellweg**

### CODE REVIEW

**Comment by mdellweg** [comment]
This might prevent things like in #116 to happen.

**Comment by akofink** [comment]
Works as expected, but it's ugly. Is there any way we could provide a easier to parse error?

```
[vagrant@centos7-hammer-devel foreman-ansible-modules]$ make test_content_view
pytest 'test/test_crud.py::test_crud[content_view]'
============================================================================================================ test session starts =============================================================================================================
platform linux2 -- Python 2.7.5, pytest-3.2.3, py-1.4.34, pluggy-0.4.0
rootdir: /home/vagrant/foreman-ansible-modules, inifile:
plugins: vcr-0.3.0
collected 1 item                                                                                                                                                                                                                              

test/test_crud.py F

================================================================================================================== FAILURES ==================================================================================================================
__________________________________________________________________________________________________________ test_crud[content_view] ___________________________________________________________________________________________________________

module = 'content_view', record = False

    @pytest.mark.parametrize('module', MODULES)
    def test_crud(module, record):
>       assert run_playbook_vcr(module, record=record) == 0
E       AssertionError: assert 2 == 0
E        +  where 2 = run_playbook_vcr('content_view', record=False)

test/test_crud.py:64: AssertionError
------------------------------------------------------------------------------------------------------------ Captured stdout call ------------------------------------------------------------------------------------------------------------

PLAY [localhost] ***************************************************************

TASK [Gathering Facts] *********************************************************
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 0}
        to retry, use: --limit @/home/vagrant/foreman-ansible-modules/test/test_playbooks/content_view.retry

PLAY RECAP *********************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1   

========================================================================================================== 1 failed in 1.46 seconds ==========================================================================================================
make: *** [test_content_view] Error 1
```

**Comment by mdellweg** [comment]
An easy solution would be to move the 'non-testing' playbooks to a different directory.

**Comment by akofink** [comment]
Hmm... actually, it's not quite working:

```sh
[vagrant@centos7-hammer-devel foreman-ansible-modules]$ make test_content_view
pytest 'test/test_crud.py::test_crud[content_view]'
============================================================================================================ test session starts =============================================================================================================
platform linux2 -- Python 2.7.5, pytest-3.2.3, py-1.4.34, pluggy-0.4.0
rootdir: /home/vagrant/foreman-ansible-modules, inifile:
plugins: vcr-0.3.0
collected 1 item                                                                                                                                                                                                                              

test/test_crud.py F

================================================================================================================== FAILURES ==================================================================================================================
__________________________________________________________________________________________________________ test_crud[content_view] ___________________________________________________________________________________________________________

module = 'content_view', record = False

    @pytest.mark.parametrize('module', MODULES)
    def test_crud(module, record):
>       assert run_playbook_vcr(module, record=record) == 0
E       AssertionError: assert 2 == 0
E        +  where 2 = run_playbook_vcr('content_view', record=False)

test/test_crud.py:64: AssertionError
------------------------------------------------------------------------------------------------------------ Captured stdout call ------------------------------------------------------------------------------------------------------------

PLAY [localhost] ***************************************************************

TASK [Gathering Facts] *********************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ImportError: No module named simplejson
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"../ansible_fail.py\", line 4, in <module>\n    import simplejson\nImportError: No module named simplejson\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 0}
        to retry, use: --limit @/home/vagrant/foreman-ansible-modules/test/test_playbooks/content_view.retry

PLAY RECAP *********************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1   

========================================================================================================== 1 failed in 1.00 seconds ==========================================================================================================
make: *** [test_content_view] Error 1
```

**Comment by akofink** [comment]
You might need to update requirements-dev.txt

**Comment by mdellweg** [comment]
Thanks, you are right. ;)

**Comment by akofink** [comment]
I like the error message.

**Pull request merged**
