### PR TITLE
Test check_mode on foreman_subnet

### PR DESCRIPTION
**Pull request by mdellweg**

### CODE REVIEW

**Comment by evgeni** [comment]
so I must admit I dislike that this blows up the fixtures by 2×

can we somehow re-use the stuff we recorded for the main tests? like instead of running it in `record_*` and `test_*` have a second `check_*` target that does the same as test but with check on?

**Comment by evgeni** [comment]
the tests fail due to a bad matcher?

**Comment by mdellweg** [comment]
The check_mode must be interleaved in the test_playbook, to test, whether it reports the right changed result.

**Comment by evgeni** [comment]
given the issue we wanted to test turned out to be not an issue, shall we still persuade this PR?

**Comment by mdellweg** [comment]
It was the matcher....

**Comment by evgeni** [comment]
needs rebase

**Comment by mdellweg** [comment]
I revoke my previous statement about interleaving.
When running the tests in replay mode, it is actually like independent tests for every task.
And while we can not run the playbook in `check_mode` against a real server, we _can_ actually do that in replay mode.
About to close this one in favour of #595 ...

**Pull request closed without merging**
