### PR TITLE
Adding test for srpm

### LINKED ISSUE #1274: verify content_upload can upload srpms
##### SUMMARY
When doing content uploads, one can set content_type to SRPM, even tho the underlying repository type is still "RPM", add a test that this actually works

##### ISSUE TYPE
 - Feature Idea

### PR DESCRIPTION
**Pull request by pipopopo**
Adding SRPM test
Signed-off-by: Kenny Tordeurs <ktordeur@redhat.com>

### CODE REVIEW

**Review by wbclark — COMMENTED** [review]
Nice find and thanks for this @pipopopo 

I think you'll need to record a new fixture (we record API responses from a live instance, so that tests in CI don't need a live instance to talk to)

to setup the test environment, you'll need to run `make test-setup` and then edit `tests/test_playbooks/vars/server.yml` to point to your live instance

for details, there is a section at https://theforeman.org/plugins/foreman-ansible-modules/ . after you select the version, on the sidebar navigate to "developer documentation" -> "testing foreman ansible modules"

Feel free to reach out if you have any questions

**Comment by pipopopo** [comment]
@wbclark thanks, yeah I was already trying that out to see how it works.

However I'm having some issues with the test:

Test failed with issue described in https://projects.theforeman.org/issues/33748

```
"Task 81561cf1-ef9f-403d-bccc-b5fc4acc681a: NameError: undefined local variable or method `upload_href' for #<Actions::Pulp3::Repository::CommitUpload:0x00007f1570349770>\nDid you mean?  uploads_api"

```

When applying that change on the test instance it fails on:

```
 "displayMessage": "Task 7972173e-2bb4-4ed4-87b5-7e39ead5a6b0: Katello::Errors::Pulp3Error: {'non_field_errors': [ErrorDetail(string='There is already a package with: arch=noarch, checksum_type=sha256, epoch=0, name=bear, pkgId=7a831f9f90bf4d21027572cb503d20b702de8e8785b02c0397445c2e481d81b3, release=1, version=4.1.', code='invalid')]}",
        "errors": [
```

I might be something wrong though as this is the first time I'm playing with this.

**Comment by evgeni** [comment]
So I thought I'd come back here, re-record the fixtures, and we can carry on…

Turns out, our "is the rpm already there" detection doesn't work for SRPMS :see_no_evil:

**Comment by evgeni** [comment]
Well, there we go, fixed code and tests pass now! :)

**Comment by pipopopo** [comment]
Nice, thanks for looking into it @evgeni !

**Review by ehelms — APPROVED** [review]

**Pull request merged**
