### PR TITLE
Foreman facts uploading correctly merges facts

### PR DESCRIPTION
**Pull request by adamruzicka**
Adapted from https://github.com/ansible/ansible/pull/51546

### CODE REVIEW

**Comment by ares** [comment]
Makes the callback work much better! :+1: (I don't have merge permissions here)

**Comment by evgeni** [comment]
@ares uh, you do!

@adamruzicka thanks! Could you please add a changelog snippet to https://github.com/theforeman/foreman-ansible-modules/tree/develop/changelogs/fragments?

**Comment by evgeni** [comment]
Also, this seems to have more changes than just the new merging? ;)

**Comment by ares** [comment]
There are several refactorings that were made in the original repo I think.

**Comment by ares** [comment]
@adamruzicka please let me know when you add a changelog, if I really have merge permissions, I'm happy to merge afterwards :-)

**Comment by adamruzicka** [comment]
Updated and the tests are :green_apple:

**Review by ares — APPROVED** [review]
Thanks @adamruzicka, merging!

**Comment by evgeni** [comment]
@ares @adamruzicka what in this PR requires requests 2.14? That's not available on EL7, making the callback less useful on one of our main platforms

**Comment by adamruzicka** [comment]
@evgeni Built in json encoding https://github.com/ansible/ansible/pull/51546/commits/11fab2dbd2410e6ec1b43e5c17d9b5329f7bfd8a

**Comment by evgeni** [comment]
So post(json=…)? Interesting.

**Comment by evgeni** [comment]
I'd argue it's there since 2.4.2 (and that's why apypie depends on >= 2.4.2): https://github.com/psf/requests/commit/8f17741849edb5e7eba0356f90cb17e43c938a2f

**Comment by adamruzicka** [comment]
cc @ekohl could the 14 be a typo?

**Comment by evgeni** [comment]
And 2.14 is from 2017: https://github.com/psf/requests/releases/tag/v2.14.0

So the explanation in that commit is wrong

**Comment by ekohl** [comment]
It does look like I made a mistake here, but at least I documented why it was needed. And the 2014 was correct :)

**Comment by adamruzicka** [comment]
Fixed in https://github.com/theforeman/foreman-ansible-modules/pull/1205

**Pull request merged**
