### PR TITLE
Allow connection parameter in dict

### PR DESCRIPTION
**Pull request by mdellweg**
Affected modules:
  * settings

Another idea from the experimental lab.
This should help passing the authentication data across files.

### CODE REVIEW

**Comment by sean797** [comment]
Interesting - To be honest, I'm not sure I like supporting 2 params for the same purpose; I think I would prefer environment vars to provide authentication options in a more scalable way

**Comment by mdellweg** [comment]
My idea is, that we could use the auth_block to have either _server:user:pass_ or _server:apitoken_.
But as the next level we could make the modules being local actions, acting on the `ansible_host` and read the credentials from facts (provided by the inventory / groupvars).

**Comment by sean797** [comment]
> My idea is, that we could use the auth_block to have either server:user:pass or server:apitoken.

@mdellweg AFAIK Foreman doesn't support `apitoken` auth.

> But as the next level we could make the modules being local actions, acting on the ansible_host and read the credentials from facts (provided by the inventory / groupvars).

Not sure I understand what you are saying, could you be more explicit?

**Comment by mdellweg** [comment]
I just figured out that you can create personal tokens via api calls. But those are actually used just like passwords. So we could at least start with an alias from token to password.

Right now, we have up to three hosts involved in every call to a module. The one, where you call ansible, the one in the inventory, where the module is executed and the foreman server. I think, it would be more natural if the host running ansible had the foreman server in its inventory (with credentials). Then you would write a play for this host, and the modules would run as local actions (like debug with access to all variables) connecting directly to api/v2.

**Comment by sean797** [comment]
Having 3 hosts just makes Ansible more flexible, you could argue if you wanted to change that it should change for every Ansible module that interacts with a servers HTTP API. 

I'd imagine most users would set at least 2 of them to be the same actual host, maybe we should default server_url to `https://{{ ansible_fqdn }}`?

If used in conjunction with other tasks in a playbook you may want to set `run_once` and/or `delegate_to`. for example 

```yaml
- hosts: all
  tasks:
    - name: promote CV
      katello_content_view_version_promote:
        username: "{{ foreman_username }}"
        password: "{{ foreman_password }}"  
        server_url: "{{ foreman_server_url }}" 
        verify_ssl: "{{ foreman_verify_ssl }}"
        name: "Fedora CV"
        organization: "Default Organization"
        from_environment: "Testing"
        to_environment: "Production"
      run_once: true
      delegate_to: "{{ nailgun_host }}"
    - name: update systems
      serial: 1
      block:
        - name: upgrade all packages
          yum:
          name: '*'
          state: latest
       - name: Restart server
         command: /sbin/shutdown -r +1
         async: 0
         poll: 0
         ignore_errors: true

       - name: Wait for the server to finish rebooting before doing the next machine
         become: false
         local_action:
           wait_for host: "{{ inventory_hostname }}"
           search_regex: OpenSSH
           port: 22
           timeout: 300
         connection: local
```

**Comment by evgeni** [comment]
I must admit I mostly run my stuff against `hosts: localhost`, so it only makes 2 hosts in my setup. (I would also not install `nailgun` on a Foreman/Katello today, as `pip install nailgun` will also pull in a new `requests` and that might have funny results in Pulp.)

Either way :-1: from me, don't see much benefit of having this (today).

**Comment by mdellweg** [comment]
It was an idea, and now it is quite old. Closing it.

**Pull request closed without merging**
