### PR TITLE
Remove local entities

### PR DESCRIPTION
**Pull request by mdellweg**
* JobTemplate
* TemplateInput
* OVirtComputeResource
* VMWareComputeResource

### CODE REVIEW

**Comment by mdellweg** [comment]
Let me look, whether i can get rid of some imports, too.

**Comment by sean797** [comment]
I guess technically this bumps the Nailgun version, should we both to update the version that's documented in every module?

**Comment by mdellweg** [comment]
Can we bump to a version, that does not yet exist?

**Comment by sean797** [comment]
I guess this is another PR blocked by Nailgun

**Comment by mdellweg** [comment]
We didn't block PR's for waiting on Nailgun Releases before, only for Nailgun PR's.
But I am fine with changing the (yet unwritten) policy here towards more reliable applicability of the modules. We should then also start to test against the released version in the master branch.

**Comment by sean797** [comment]
Yes, I don't really want to block this on a Nailgun release. Maybe when we do FAM releases we just bump the Nailgun version for all modules regardless?

**Comment by sean797** [comment]
@mdellweg mind rebasing? Then lets just merge this

**Pull request merged**
