### PR TITLE
add ip, mac, comment, owner and root_pass to host module

### PR DESCRIPTION
**Pull request by evgeni**
root pass is also added to hostgroup via the shared params.

### CODE REVIEW

**Comment by itcultus** [comment]
I will try this week.

**Comment by evgeni** [comment]
@itcultus any luck trying this out?

**Comment by evgeni** [comment]
ping @itcultus 

I'm going to merge this this Friday unless you object until then :)

**Comment by itcultus** [comment]
Please do so!
We include the modules as collections and thus we will test it soon.

**Comment by itcultus** [comment]
Is there any possibility to update the documents in https://www.theforeman.org/plugins/foreman-ansible-modules/sphinx/modules/foreman_host_module.html#foreman-host-module ? 

I would probably test the code this week extensively ( I need to create/delete a few VMs in our environment). So, I need to know how you define the ip/mac etc. Of course I can check the code, but the document is better for the rest of the admins here.

**Comment by evgeni** [comment]
You can run `ansible-doc theforeman.foreman.foreman_host` if you have the collection installed. I'll take care of updating the online docs later today.

**Comment by evgeni** [comment]
I've opened a PR to update the online docs here: https://github.com/theforeman/theforeman.org/pull/1538

**Comment by itcultus** [comment]
Better now :)
Thank you. 
I will inform you about the status

**Pull request merged**
