### PR TITLE
use foreman 2.1 container in tests

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Comment by evgeni** [comment]
that would have been too easy

**Comment by mdellweg** [comment]
Looks like the container starts successfully one in six times. ;)

**Comment by evgeni** [comment]
0/6 -- we don't start it on 2.8 ;)

**Comment by evgeni** [comment]
this is now using a PostgreSQL container as 2.1 dropped SQLite "support", which should also have the benefit of being more stable as the issues we've seen in the past were usually because of SQLite locks

**Pull request merged**
