### PR TITLE
Foreman_subnet: add IPAM choice None

### PR DESCRIPTION
**Pull request by Boulet-**
Module: foreman_subnet
API Url: https://theforeman.org/api/1.23/apidoc/v2/subnets/create.html

This PR adds a new choice "None" for the IPAM option.

Let me know if I forgot something.

### CODE REVIEW

**Comment by mdellweg** [comment]
It would be nice, if you could add a test for this. I am wondering, whether `None` is really the literal string `"None"` or an unset parameter. (Looking at the apidoc it could even be both.) In the latter case, i think we need to pass a python `None` to the api in order to unset it.

**Comment by evgeni** [comment]
I think it's a literal "None", but yeah, a test would be nice :)

**Comment by evgeni** [comment]
Hi @Boulet-, thanks for your PR! I wanted to reach out and ask if you're planning to add tests for this feature or if you don't have enough time to dive into our tests. The later is absolutely fine, the change looks fine and given it just adds another type of IPAM, I'm OK with merging it without tests.

**Comment by evgeni** [comment]
we discussed this during triage on Friday, and decided this does not require tests. merging.

**Comment by Boulet-** [comment]
Sorry for the late answer, thanks a lot for the merge :)
I'll try to add tests on next MRs.

**Pull request merged**
