### PR TITLE
add http_proxy module

### PR DESCRIPTION
**Pull request by evgeni**
Fixes: #867

### CODE REVIEW

**Comment by evgeni** [comment]
Actually, no, the username handling is broken

**Comment by evgeni** [comment]
now with 100% more correct tests :)

**Comment by evgeni** [comment]
that ci issue is ansible, not us :(

**Comment by evgeni** [comment]
the 3.7 devel failure should be fixed by https://github.com/theforeman/foreman-ansible-modules/pull/875

**Comment by mdellweg** [comment]
Seems like the pipelines for 3.6 also installs ansible from pypi. It just does not fail with it.

**Comment by evgeni** [comment]
failures unrelated :see_no_evil:

**Pull request merged**
