### PR TITLE
test ansible/devel on Python 3.8

### PR DESCRIPTION
**Pull request by evgeni**
Includes #692 to see if stuff is green :)

### CODE REVIEW

**Comment by evgeni** [comment]
```
ERROR: plugins/module_utils/foreman_helper.py:13:0: syntax-error: Cannot import 'contextlib' due to syntax error 'invalid syntax (&lt;unknown&gt;, line 380)'
ERROR: plugins/module_utils/foreman_helper.py:15:0: syntax-error: Cannot import 'collections' due to syntax error 'invalid syntax (&lt;unknown&gt;, line 96)'
ERROR: plugins/module_utils/foreman_helper.py:16:0: syntax-error: Cannot import 'functools' due to syntax error 'invalid syntax (&lt;unknown&gt;, line 276)'
ERROR: plugins/modules/foreman_host.py:164:4: not-context-manager: Context manager 'generator' doesn't implement __enter__ and __exit__.
```

**Comment by evgeni** [comment]
@gundalow this is what I mentioned during cfgmgmtcamp to you: the sanity tests fail on Python 3.8, with no apparent reason :(

**Comment by gundalow** [comment]
@evgeni oh, that is strange. Could you please remind me about this next week? I'm back at work on Tuesday.

**Comment by evgeni** [comment]
@gundalow luckily, I've been able to trace that to a "bad" pylint dependency, see https://github.com/ansible/ansible/issues/67118

**Comment by evgeni** [comment]
I have disabled sanity tests for 3.8 until https://github.com/ansible/ansible/issues/67118 is resolved

**Comment by evgeni** [comment]
3.6 ia the default Python on EL8, so I'd rather not remove it. And 3.7 is used for almost everything that is not matrixed today.

**Comment by evgeni** [comment]
We probably could drop 3.5?

**Comment by mdellweg** [comment]
I thought having the smalles and the biggest 3.* version we support in the matrix was not a bad idea.
how many jobs are we adding here?

**Pull request merged**
