### PR TITLE
add external ipam to subnet module

### LINKED ISSUE #966: Handle subnets thats use external IPAM like phpIPAM
We configure our whole foreman server via ansible and we use phpIPAM as external IP address management. Is there a way to configure subnet via ansible which use an external IPAM. We don't found any hints in documentation. On the contrary we found this for IPAM:

```
DHCP
Internal DB
Random DB
EUI-64
None
```

Where `DHCP` is the default. No idea whether the plugin (in this case smart_proxy_ipam) have to/should/can add the needed fields to API.

### PR DESCRIPTION
**Pull request by evgeni**
Fixes: #966

### CODE REVIEW

**Review by mdellweg — APPROVED** [review]
I give it a :+1: codewise.
A confirmation it solves #966 would be good.

**Comment by cmeissner** [comment]
@mdellweg not sure if the change is enough. If I select `External IPAM` I get an extra field `External IPAM Group`. This is not known with your code change i guess.

**Comment by evgeni** [comment]
what can you select there? in the API, I only see "external ipam proxy" which is the smart proxy running the ipam I guess.

here is the api documentation I am looking at: https://theforeman.org/api/2.1/apidoc/v2/subnets/create.html

**Comment by evgeni** [comment]
Reading the code, it seems the group is not exposed via the API :(

**Comment by cmeissner** [comment]
Here you see a screenshot of the UI.

image

Not so good that the field isn't exposed. So the work is harder than expected, I guess.

**Comment by evgeni** [comment]
@cmeissner how useful (or not?) is it to set the subnet to "external" but not being able to select a group? the UI says "optional", so I'd guess it's still a bit useful?

**Comment by cmeissner** [comment]
For our use case we grouping dozen of ip networks to a given site in this groups aka sections in phpIPAM. So we unfortunately need this field. :-(

**Comment by evgeni** [comment]
but in a simpler setup, this would work without, right?

I'll open an issue against Foreman to expose that via the API, but don't expect a too quick turn around.

**Comment by cmeissner** [comment]
Maybe it would work but we can't test it this way. 

Thanks for opening the issue against Foreman but I am afraid that we need to find a workaround for that.

How long will it last that the above change is in a new ansible-modules version available? So we can set configure the subnets for external IPAM and its smart-proxy and only have to set the IPAM group for each by bio script.

**Comment by evgeni** [comment]
I am planning a release (to galaxy) probably tomorrow.
Can you by any chance test before the release? Otherwise I'd merge what we have and you ping us when you installed the new version.

**Comment by mdellweg** [comment]
Is it possible that the optional option is only missing from the apipie docs? (We had that before...)

Edit: Too sad, but i found nothing in the api controller.

**Comment by evgeni** [comment]
@mdellweg no, the controller doesn't know about it.

I've opened https://projects.theforeman.org/issues/30890

**Comment by cmeissner** [comment]
> Can you by any chance test before the release? Otherwise I'd merge what we have and you ping us when you installed the new version.

I can not promise anything, but I'll try it tomorrow morning to test it locally if I found time.

**Comment by cmeissner** [comment]
@evgeni I've tested your change, it works as expected. 
Thanks for quick response.

As long as we don't use same subnets in different sections we can live without the group field otherwise we have to add the value by hand.

Can you give me a ping please if the new version is published to galaxy?

**Comment by evgeni** [comment]
@cmeissner cool, thanks a ton for testing this!

I'll ping you on the release PR and you can expect it to land on galaxy something like 10 minutes after the PR is merged (yay, automation!)

**Pull request merged**
