### PR TITLE
Replace hostname in fixture writing

### LINKED ISSUE #706: Rewrite URL in fixtures
It should be possible to hook into the vcr persister to always rewrite the server url to foreman.example.org.

I have seen people doing this manually, and I don't like those files to be touched by humans.

### PR DESCRIPTION
**Pull request by mdellweg**
Fixes #706

### CODE REVIEW

**Comment by mdellweg** [comment]
@nesanton ?

**Comment by nesanton** [comment]
oooooh this looks good! No more sed

**Comment by evgeni** [comment]
Do we *really* need this urlparse/urlunparse abomination? But if it works...

**Comment by mdellweg** [comment]
```
request.host = "foreman.example.org"
<...>
"msg": "Failed to connect to Foreman server: can't set attribute"
```
Seems to be read only.

**Comment by evgeni** [comment]
Thanks for trying!

**Pull request merged**
