### PR TITLE
add OpenStack to compute_resource

### LINKED ISSUE #1640: Add provider OpenStack to foreman_compute_resource
##### SUMMARY
It would be great to set up the provider OpenStack with the module foreman_compute_resource

##### ISSUE TYPE
 - Feature Idea

### PR DESCRIPTION
**Pull request by alesc**
Resolves #1640

### CODE REVIEW

**Comment by evgeni** [comment]
From a first glance, this looks good (ignore the Python 2.7 error, it's not your code).

I'd be OK with merging this without additional tests added, as long as the old ones pass (they do).

Is there anything more left on your side? (You marked the PR as draft)

**Comment by alesc** [comment]
This PR is still a draft because even if it works at first pass, the 2nd pass fail.

```
TASK [set compute resource] ****************************************************
fatal: [localhost]: FAILED! => {
  "changed": false,
  "error": {
    "errors": {
      "provider": [
        "cannot be changed",
        "is not included in the list"
      ]
    },
    "full_messages": [
      "Provider cannot be changed",
      "Provider is not included in the list"
    ],
    "id": 34
  },
  "msg": "Error while performing update on compute_resources: 422 Client Error: Unprocessable Entity for url: https://foreman.lab/api/compute_resources/34"
}
```

Maybe the provider param should not be sent in the api call.
Any idea ?

**Comment by evgeni** [comment]
can you post the output of `ansible-playbook --diff --check <the_playbook.yml>`? I wonder why it tries to change the provider at all.

**Comment by alesc** [comment]
That's an case issue, `OpenStack` != `Openstack`  
I will recheck my change.

```
$ ansible-playbook --diff --check ansible/foreman.yml
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that
the implicit localhost does not match 'all'
PLAY [localhost] ***************************************************************
TASK [Get organization data] ***************************************************
ok: [localhost]
TASK [set foreman location] ****************************************************
ok: [localhost]
TASK [set compute resource] ****************************************************
--- before
+++ after
@@ -10,9 +10,10 @@
             "organization_ids": [
                 4
             ],
+            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
             "project_domain_id": "xxx",
             "project_domain_name": "lab",
-            "provider": "Openstack",
+            "provider": "OpenStack",
             "tenant": "TEST",
             "url": "https://openstack.lab:5000/v3",
             "user": "xxx"
changed: [localhost]
```

**Comment by evgeni** [comment]
huh, yeah... let's try with `Openstack` then

**Comment by alesc** [comment]
From foreman api : 

```
      "provider": "Openstack",
      "provider_friendly_name": "OpenStack",
```

Curently testing with Openstack in compute_resource module  ...

**Comment by evgeni** [comment]
`provider` is what everything machine should be using (and what is stored in the DB), `provider_friendly_name` is what gets displayed in the UI for users.

Ansible... would use `provider`

**Review by evgeni — APPROVED** [review]

**Comment by evgeni** [comment]
Thanks a ton!

**Pull request merged**
