### PR TITLE
add os_default_template to tests

### PR DESCRIPTION
**Pull request by MarkusTeufelberger**
This module (and some others) don't seem to be tested by Travis.

### CODE REVIEW

**Comment by MarkusTeufelberger** [comment]
As far as I understand your testing process, this should have failed because there are no recorded fixtures for this module yet, right?! O_o

**Comment by akofink** [comment]
Hmm... it does show 13 tests, up from 12. :man_shrugging:

**Comment by akofink** [comment]
Oh! It's the inventory. You need to change the `hosts: localhost` part of `os_default_template.yml` to `hosts: tests`

**Comment by mdellweg** [comment]
I guess, this is a duplicate to #102 .
The 'search' problem will go away as soon as a new nailgun-release is out there (see https://github.com/SatelliteQE/nailgun/issues/488)

**Comment by akofink** [comment]
Yeah, it's working for me locally (getting an expected VCR error). I was using an old version of Nailgun locally.

**Comment by mdellweg** [comment]
With #102 merged, i think we can close this one.

**Pull request closed without merging**
