### PR TITLE
Add source url param to Katello module

### PR DESCRIPTION
**Pull request by chris1984**

### CODE REVIEW

**Comment by chris1984** [comment]
@sean797 where else an I supposed to add it?

**Comment by evgeni** [comment]
I think this is missing to pass the new param to the Katello API.

**Comment by chris1984** [comment]
Closing as this is not needed.

**Comment by chris1984** [comment]
This is pending a merge of this:

https://github.com/Katello/katello/pull/7594

Once that gets added I will update this PR.

**Pull request closed without merging**
