### PR TITLE
Fix test dependencies

### PR DESCRIPTION
**Pull request by mdellweg**
Very much unhappy here, but somhow the tests are passing again.
I have no idea, which dependency broke them, and am not sure, what would be the best practice with requirements.

### CODE REVIEW

**Comment by mdellweg** [comment]
Tests went back to normal.
Do you all think, we might freeze the python packages anyway?
If so, should we define a way to extract them from travis as a build artifact?

**Comment by sean797** [comment]
I don't think this actually fixes it, looking at #137 the problem seems to be with the custom matcher. By the looks of things, this isn't really required?

**Comment by mdellweg** [comment]
Now this is really strange. I know for sure we needed the custom matcher back then (we had either python2 or python3 passing the tests). And last week the tests were (despite one) all broken on all branches, which could have only been unforseen changes in the dependencies.
As everything is green again, i'm fine with closing this.

**Comment by sean797** [comment]
I suspect one of our deps broke something, im not sure which one, and they have since fixed it.

:+1: to closing and removing the custom matcher.

**Pull request closed without merging**
