### PR TITLE
document repo_set without release

### PR DESCRIPTION
**Pull request by sean797**
Currently repo set is broken due to https://github.com/SatelliteQE/nailgun/issues/457#issuecomment-346649087 but there is a workaround on that issue.

### CODE REVIEW

**Comment by ekohl** [comment]
There's a typo in the document (commit message/PR title)

**Comment by sean797** [comment]
me 👎

**Comment by akofink** [comment]
What's the status of this PR? The example doesn't work because of the nailgun issue?

**Comment by sean797** [comment]
Turns that that was because I and some others were using lastest nailgun version with Satellite 6.2 (they have a separate 6.2 branch).

This is ready for merge.

**Pull request merged**
