### PR TITLE
Require git version of nailgun

### PR DESCRIPTION
**Pull request by ares**
Without this I was getting "cannot import name File"

### CODE REVIEW

**Comment by mdellweg** [comment]
Not entirely sure, this is related to #185 .
But i would prefer, if we could 'cool' down these modules to work with an actually released version of nailgun.

**Comment by sean797** [comment]
> But i would prefer, if we could 'cool' down these modules to work with an actually released version of nailgun

That would be nice, but I suspect quite a hard goal to realise.

I think the solution, at least in the short term, is to work with SatelliteQE and do another PyPi release?

**Comment by mdellweg** [comment]
Another solution could be, to tag a release here, the moment we have a new nailgun version.

**Comment by ehelms** [comment]
I suggested this change for @ares to open up. We test against this same version (https://github.com/theforeman/foreman-ansible-modules/blob/master/requirements-dev.txt#L4) so we should have master be against it as well.

**Comment by mdellweg** [comment]
> I'm not fussed either way really. I think we need to have a discussion and nail down how we do FAM releases ;)

We should use a hammer or a nailgun. ;)
I am :+1: for releases with a version of nailgun.

**Comment by evgeni** [comment]
so, given #261, should we still have this? or just go all in on `apypie`?

**Comment by mdellweg** [comment]
I dont think it hurts.

**Comment by ares** [comment]
Closing, let me know if you want me to reopen :-)

**Pull request closed without merging**
