### PR TITLE
Add 'None' as an option for pxe-loader

### LINKED ISSUE #971: Support 'None' Option for PXE Loader Selection
##### SUMMARY
'None' is an option within the webUI and the API, however the modules currently reject the option before firing off an API call.

##### FIX
Within plugins/module_utils/foreman_helper.py, add 'None' to pxe_loader=dict(choices)

### PR DESCRIPTION
**Pull request by jjaswanson4**
This option is selectable in the WebUI and available via the satellite API

### CODE REVIEW

**Comment by jjaswanson4** [comment]
[Related Issue](https://github.com/theforeman/foreman-ansible-modules/issues/971)

**Comment by evgeni** [comment]
Thanks! Can you please also add it to the documentation in https://github.com/theforeman/foreman-ansible-modules/blob/b80473506bf0eed3e864e4c6d13eea1b19b540e1/plugins/doc_fragments/foreman.py#L195-L213

**Comment by jjaswanson4** [comment]
> Thanks! Can you please also add it to the documentation in
> 
> https://github.com/theforeman/foreman-ansible-modules/blob/b80473506bf0eed3e864e4c6d13eea1b19b540e1/plugins/doc_fragments/foreman.py#L195-L213

Yes, commit 682fdcd1eae1364965bf863fbfd3ab25c561433d adds this to the documentation:

https://github.com/theforeman/foreman-ansible-modules/blob/682fdcd1eae1364965bf863fbfd3ab25c561433d/plugins/doc_fragments/foreman.py#L195-L214

**Comment by evgeni** [comment]
oh, and can you please add a changelog entry to `changelogs/fragments/`? something like `changelogs/fragments/971-pxe_loader-none.yaml`:

```yaml
bugfixes:
  - host, hostgroup - support ``None`` as the ``pxe_loader`` (https://github.com/theforeman/foreman-ansible-modules/issues/971)
```

**Comment by jjaswanson4** [comment]
> oh, and can you please add a changelog entry to `changelogs/fragments/`? something like `changelogs/fragments/971-pxe_loader-none.yaml`:
> 
> ```yaml
> bugfixes:
>   - host, hostgroup - support ``None`` as the ``pxe_loader`` (https://github.com/theforeman/foreman-ansible-modules/issues/971)
> ```

Yes, 6be28cc418c26ff8e0ada77ff6e18f40095e40b9 creates that file. Should I edit anything in https://github.com/theforeman/foreman-ansible-modules/blob/develop/changelogs/changelog.yaml ?

**Review by evgeni — APPROVED** [review]

**Comment by evgeni** [comment]
no, the rest is automated at release time, thanks a ton!

**Pull request merged**
