### PR TITLE
rename verify_ssl to validate_certs

### PR DESCRIPTION
**Pull request by evgeni**
Ansible 2.8 moved to a common "validate_certs" param for TLS certificate
validation (see [1]), let's move with it.

This adds an alias, so old playbooks should still work.

[1] https://github.com/ansible/ansible/blob/stable-2.8/changelogs/CHANGELOG-v2.8.rst

### CODE REVIEW

**Comment by evgeni** [comment]
let's figure out why the tests failed

**Comment by mdellweg** [comment]
First guess: It's the new ansible version.
https://travis-ci.org/theforeman/foreman-ansible-modules/jobs/534754127#L278

**Comment by evgeni** [comment]
@mdellweg yeah, from IRC:

```
10:42 < Zhenech> great, ansible 2.8 broke f-ansible-modules tests
```

**Comment by evgeni** [comment]
valid failures now

**Comment by evgeni** [comment]
fixed the errors, accidentally changed too many module tests.

@ehelms @ekohl @mdellweg any last minute wishes?

**Comment by mdellweg** [comment]
I think, it's fine. Did you not promise to make such transitions easier with the doc-snippets?

**Comment by evgeni** [comment]
@mdellweg me?! promise?! yes, but post-2.8 as that snippet thing is a 2.8 feature :)

**Comment by mdellweg** [comment]
So can we drop <= 2.8 already? :smiling_imp:

**Pull request merged**
