### PR TITLE
Check for missing commits vs devel for inventory plugin

### PR DESCRIPTION
**Pull request by willtome**
diff against ansible-collection-migration/theforeman.foreman for `plugins/inventory/foreman.py` taking into account changes from #591

### CODE REVIEW

**Comment by evgeni** [comment]
I guess this shall tackle #729?

Looking at both `ansible/ansible:devel` and `ansible-collection-migration/theforeman.foreman:master`, I see the following unaddressed diff:

```diff
--- plugins/inventory/foreman.py	2020-03-10 08:27:11.851327440 +0100
+++ /home/evgeni/Devel/ansible/ansible/lib/ansible/plugins/inventory/foreman.py	2020-03-03 17:34:28.410870683 +0100
@@ -64,18 +64,17 @@
         type: boolean
         default: False
         version_added: '2.10'
-      legacy_hostvars:
-        description:
-            - Toggle, if true the plugin will build legacy hostvars present in the foreman script
-            - Places hostvars in a dictionary with keys `foreman`, `foreman_facts`, and `foreman_params`
+      want_ansible_ssh_host:
+        description: Toggle, if true the plugin will populate the ansible_ssh_host variable to explicitly specify the connection target
         type: boolean
         default: False
         version_added: '2.10'
+
 '''
 EXAMPLES = '''

@@ -209,13 +208,6 @@
             raise ValueError("More than one set of facts returned for '%s'" % host)
         return facts
 
-    def _get_hostvars(self, host, vars_prefix='', omitted_vars=()):
-        hostvars = {}
-        for k, v in host.items():
-            if k not in omitted_vars:
-                hostvars[vars_prefix + k] = v
-        return hostvars
-
     def _populate(self):
 
         for host in self._get_hosts():
@@ -230,31 +222,20 @@
                     group_name = self.inventory.add_group(group_name)
                     self.inventory.add_child(group_name, host_name)
 
-                if self.get_option('legacy_hostvars'):
-                    hostvars = self._get_hostvars(host)
-                    self.inventory.set_variable(host_name, 'foreman', hostvars)
-                else:
-                    omitted_vars = ('name', 'hostgroup_title', 'hostgroup_name')
-                    hostvars = self._get_hostvars(host, self.get_option('vars_prefix'), omitted_vars)
-
-                    for k, v in hostvars.items():
+                # set host vars from host info
+                try:
+                    for k, v in host.items():
+                        if k not in ('name', 'hostgroup_title', 'hostgroup_name'):
                         try:
-                            self.inventory.set_variable(host_name, k, v)
+                                self.inventory.set_variable(host_name, self.get_option('vars_prefix') + k, v)
                         except ValueError as e:
                             self.display.warning("Could not set host info hostvar for %s, skipping %s: %s" % (host, k, to_text(e)))
+                except ValueError as e:
+                    self.display.warning("Could not get host info for %s, skipping: %s" % (host_name, to_text(e)))
 
                 # set host vars from params
                 if self.get_option('want_params'):
-                    params = self._get_all_params_by_id(host['id'])
-                    filtered_params = {}
-                    for p in params:
-                        if 'name' in p and 'value' in p:
-                            filtered_params[p['name']] = p['value']
-
-                    if self.get_option('legacy_hostvars'):
-                        self.inventory.set_variable(host_name, 'foreman_params', filtered_params)
-                    else:
-                        for k, v in filtered_params.items():
+                    for p in self._get_all_params_by_id(host['id']):
                             try:
                                 self.inventory.set_variable(host_name, p['name'], p['value'])
                             except ValueError as e:
@@ -280,6 +261,17 @@
                             except ValueError as e:
                                 self.display.warning("Could not create groups for host collections for %s, skipping: %s" % (host_name, to_text(e)))
 
+                # put ansible_ssh_host as hostvar
+                if self.get_option('want_ansible_ssh_host'):
+                    for key in ('ip', 'ipv4', 'ipv6'):
+                        if host.get(key):
+                            try:
+                                self.inventory.set_variable(host_name, 'ansible_ssh_host', host[key])
+                                break
+                            except ValueError as e:
+                                self.display.warning("Could not set hostvar ansible_ssh_host to '%s' for the '%s' host, skipping: %s" %
+                                                     (host[key], host_name, to_text(e)))
+
                 strict = self.get_option('strict')
 
                 hostvars = self.inventory.get_host(host_name).get_vars()
```

**Comment by evgeni** [comment]
ping @willtome @gundalow

**Comment by gundalow** [comment]
If you are happy, I'm happy :)

**Comment by willtome** [comment]
want_ansible_ssh_host was dropped in favor of using compose vars since the plugin not implements this functionality.

**Comment by evgeni** [comment]
@willtome where and when? I don't see such a change neither in `ansible/ansible:devel` nor `ansible-collection-migration/theforeman.foreman:master`. Or am I looking at the wrong branches?

**Comment by willtome** [comment]
@evgeni Here is where `legacy_hostvars` was ported from ansible/ansible and dropped `want_ansible_ssh_host` https://github.com/willtome/foreman-ansible-modules/pull/2. @jladdjr tested that compose/constructed would provide the backwards compatibility he was implementing like this 
```
compose:
  ansible_ssh_host: foreman['ip6'] | default(foreman['ip'], true)
```

**Comment by evgeni** [comment]
Ah, you had an intermediate repo where you tested against awx. Ok, gotcha!

**Pull request merged**
