### PR TITLE
use FQCN in EXAMPLES

### PR DESCRIPTION
**Pull request by evgeni**
refs #910 and #911

### CODE REVIEW

**Review by mdellweg — APPROVED** [review]
I fail to see, why this is especially desirable, but there seems to be no notion of "in the scope of the collection" in ansible.

**Comment by evgeni** [comment]
to make them copy-paste-able, I guess

**Comment by mdellweg** [comment]
I was thinking it makes it hard to maintain a closely following fork of the repository, but we have lost that with the crazy import statements already.

**Comment by evgeni** [comment]
> I was thinking it makes it hard to maintain a closely following fork of the repository, but we have lost that with the crazy import statements already.

nah, it's not that hard ;)

https://github.com/RedHatSatellite/satellite-ansible-collection/blob/master/Makefile#L115-L117

**Pull request merged**
