### PR TITLE
WIP/RFC: Use 'vars_files' and 'module_defaults' to DRY test_playbooks.

### PR DESCRIPTION
**Pull request by mdellweg**
Given the current implementation with the tasks files, the benefit is small, but i wanted to show this new finding around anyway.

### CODE REVIEW

**Comment by mdellweg** [comment]
I tend to say, the test failures are unrelated.

**Comment by mdellweg** [comment]
I decided to split this pr in two parts. The `vars_files' version has benefits on its own.

https://github.com/theforeman/foreman-ansible-modules/pull/302

**Comment by mdellweg** [comment]
Maybe not the best way, but the first one i came up with:
https://github.com/ansible/ansible/pull/58070

**Comment by evgeni** [comment]
@mdellweg what's the state of this? I see the referenced ansible PR was closed as "we'll do something different" without saying what will be done.

Is this PR valuable as it is -- if so, please rebase it.
Otherwise I'd tend to closing it, or at least marking as "needs other PR" and stash it somewhere deep.

**Comment by mdellweg** [comment]
I think, no. I would really have loved to learn, _what_ they are planning there. Should we all nudge them for a better answer?

**Pull request closed without merging**
