### PR TITLE
always provide a basearch when enabling a repository_set

### PR DESCRIPTION
**Pull request by evgeni**
Fixes: #453

### CODE REVIEW

**Comment by evgeni** [comment]
this is missing tests for the added code, but I'd like to add them only after #650 has been merged as it includes great reshuffling of the repo_set test playbook

**Comment by evgeni** [comment]
@nesanton

**Comment by nesanton** [comment]
looks ok

**Comment by evgeni** [comment]
Interestingly, this breaks idempotency of this module, as the repo name differs.

When listing, I get `Red Hat Enterprise Linux 8 for x86_64 - BaseOS RPMs 8`, but after enabling (both, UI and API with this PR applied), I see `Red Hat Enterprise Linux 8 for x86_64 - BaseOS RPMs x86_64 8`.

And this does not bode well with the rest of the detection logic.

**Comment by evgeni** [comment]
So, after debugging this further, I've opened https://projects.theforeman.org/issues/28555 and https://projects.theforeman.org/issues/28644 and would like not to merge this PR until we have clear guidance from Katello what is going on there.

**Comment by evgeni** [comment]
`basearch` gets pruned from repos that don't have that substitution in katello 3.16, see https://projects.theforeman.org/issues/28644

I am thus closing this PR as "invalid" and the issue it fixes as "notabug"

**Pull request closed without merging**
