### PR TITLE
Fix Job Template module

### PR DESCRIPTION
**Pull request by mdellweg**
'template_input_list' should not be undefined.

### CODE REVIEW

**Comment by mdellweg** [comment]
See also: https://github.com/theforeman/foreman_remote_execution/pull/373

**Comment by sean797** [comment]
ping @manuelbonk, I think your Nailgun PR will require the same changes?

**Comment by manuelbonk** [comment]
@sean797 thanks, I renamed the parameter there too.

**Comment by sean797** [comment]
Thanks @mdellweg :+1:

**Pull request merged**
